version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: src/DistributedInventory.Api/Dockerfile
    container_name: distributed-inventory-api
    ports:
      - "5000:8080"
    environment:
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data

  worker:
    build:
      context: .
      dockerfile: src/DistributedInventory.Workers/Dockerfile
    container_name: distributed-inventory-worker
    depends_on:
      - api
    environment:
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
